### ISSUE TITLE
screensaver only appears in the lower left corner

### ISSUE THREAD

**Issue by MariusQuabeck** [pedrommcarrasco/Brooklyn#67]
see title, for some reason I can only see a minimalized screensaver instead of fullscreen, see picture attached. 

MacBook Pro 15" 2019

let me know if there is anything I can do to help you debug this :)

![IMG_4972](https://user-images.githubusercontent.com/17063564/71517664-6d845b80-28af-11ea-87ac-9e16381b94e4.JPG)

**Comment by pedrommcarrasco** [comment]
You're not the first one to report this and it's a _not so cool_ one

I'll try to take a look into it early next year, in the meantime can you try the famous "reinstall" and see if it works? 😅 

https://github.com/pedrommcarrasco/Brooklyn/issues/66

**Comment by MariusQuabeck** [comment]
Hi Pedro,

I just reinstalled it, it worked like twice and now it's back in the lower-left corner

**Comment by pedrommcarrasco** [comment]
Sounds like I'll have some fun 😓 
Going to be a hard one since I can't reproduce it but let's have hope!

**Comment by MariusQuabeck** [comment]
again let me know if you need me to debug anything :)

enjoy your holidays!

**Comment by hanspeteroliver** [comment]
I am experiencing the same issue sporadically, because if that it's really hard to reproduce it.

**Comment by Theragus** [comment]
Same here but it only occurs on my external 4K Monitor when i have the lid closed on the MBP. While it's open the Screensaver has the normal size on both screens (External and Internal).

**Comment by gustavo-rivera-tierconnect-com** [comment]
This is happening to me also on my Macbook Pro 2018, without external displays or anything.
If it helps this is also happening with SaveHollywood screensaver.

**Comment by xGameBomber** [comment]
It makes the same with other third-part screensavers idk why

**Comment by fletech** [comment]
I made this:
The file Brooklyn.Saver has been intalled and left on the file where I did the download, so I moved it from Desktop towards its path, which is:
/Users/USERNAME/Library/Screen Savers.
I've fixed it like this.
Cheers!

**Comment by smolz** [comment]
2017 Macbook Pro 15" same issue. tried downloading it (works a couple of time), tried installing with Brew with the same results.

**Comment by waterwriter3** [comment]
I have tried this, and the minimization still occurs on screen, any new thoughts?

**Comment by waterwriter3** [comment]
> I made this:
> As I downloaded the installer on Desktop, I've left it in there. Then I installed it but I saw this common issue when it began to run. So I moved it from Desktop towards its path, which is:
> /Users/USERNAME/Library/Screen Savers.
> I've fixed it like this.
> Cheers!

I have attempted the fix suggested here with no resolve, the issue is the same of a minimized screen saver in the lower left corner. Any new thoughts or updates to this issue?
